DROP TABLE IF EXISTS hewan;
CREATE TABLE hewan (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    jenis TEXT NOT NULL,
    keterangan TEXT NOT NULL,
    berat INTEGER
);
DROP TABLE IF EXISTS penerima;
CREATE TABLE penerima (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    nama TEXT NOT NULL,
    umur INTEGER,
    fakir INTEGER NOT NULL DEFAULT 0,
    miskin INTEGER NOT NULL DEFAULT 0,
    fisabilillah INTEGER NOT NULL DEFAULT 0,
    mualaf INTEGER NOT NULL DEFAULT 0,
    gharim INTEGER NOT NULL DEFAULT 0,
    ibnusabil INTEGER NOT NULL DEFAULT 0,
    amil INTEGER NOT NULL DEFAULT 0,
    bobot INTEGER NOT NULL DEFAULT 0,
    layak INTEGER NOT NULL DEFAULT 0
);